In [85]:
from pyspark import SparkContext, SparkConf
import pandas as pd
from operator import add

In [86]:
spark = SparkSession \
    .builder \
    .appName("Ethical Facial Recognition") \
    .getOrCreate()

In [87]:
file_name = "X_small_test.csv"
# file_path = 'https://storage.googleapis.com/uga-dsp/project2/files/' + file_name
file_path = 'dataset/' + file_name
# print(file_path)

In [88]:
df = spark.read.format('csv') \
                .option('header',True) \
                .option('multiLine', True) \
                .load(file_path)
panda_df = df.toPandas()

In [89]:
panda_df.drop(panda_df.columns[[0,1,2,3,4,5,6,7,8]], axis=1, inplace=True)
panda_df

,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,...,fc1,fc2,fc3,fc4,fc5,fc6,fc7,fc8,fc9,Sex (subj)
0,178.0,126.0,179.0,137.0,180.0,147.0,182.0,157.0,186.0,166.0,...,-0.0108,-0.0252,-0.0307,-0.2466,-0.0171,-0.0245,-0.0465,-0.0,-0.0037,1
1,154.0,149.0,157.0,158.0,159.0,167.0,161.0,176.0,164.0,184.0,...,-0.2105,0.0102,0.0055,-0.503,-0.01,-0.0006,-0.3122,-0.0006,0.0154,0
2,317.0,135.0,318.0,156.0,320.0,176.0,324.0,196.0,333.0,214.0,...,0.0001,-0.0015,-0.0098,-0.1621,-0.0258,-0.0278,-0.0173,-0.0018,0.0043,0
3,165.0,158.0,165.0,167.0,165.0,174.0,166.0,182.0,167.0,190.0,...,-0.0667,0.0365,0.0029,-0.1392,-0.0368,-0.0364,-0.1145,-0.0029,-0.0035,1
4,125.0,172.0,126.0,183.0,127.0,192.0,129.0,202.0,131.0,211.0,...,-0.0493,0.036000000000000004,-0.0092,-0.1548,0.0062,-0.0135,-0.1543,0.0013,-0.0082,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,98.0,154.0,101.0,160.0,104.0,166.0,107.0,172.0,111.0,177.0,...,-0.1187,0.0007,-0.0194,-0.0991,-0.0151,-0.0079,-0.1023,-0.0078,-0.0048,0
259,210.0,106.0,208.0,127.0,207.0,150.0,209.0,174.0,214.0,196.0,...,-0.0721,0.0159,-0.0135,-0.0944,-0.0183,-0.0143,-0.134,-0.0182,-0.0109,0
260,185.0,142.0,187.0,152.0,190.0,161.0,193.0,170.0,197.0,178.0,...,-0.0041,0.0315,-0.0081,-0.1893,-0.0066,-0.0322,-0.1074,0.0023,-0.006,1
261,144.0,91.0,141.0,99.0,139.0,108.0,137.0,117.0,136.0,126.0,...,-0.1416,0.0501,0.0026,-0.267,-0.0232,-0.049,-0.0559,0.011000000000000001,0.0104,0
262,133.0,137.0,132.0,145.0,131.0,153.0,130.0,162.0,131.0,171.0,...,-0.2216,-0.0287,-0.0599,-0.2705,-0.0529,-0.0638,-0.247,0.0254,-0.0506,0

In [90]:
panda_df.head(5)

,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,...,fc1,fc2,fc3,fc4,fc5,fc6,fc7,fc8,fc9,Sex (subj)
0,178.0,126.0,179.0,137.0,180.0,147.0,182.0,157.0,186.0,166.0,...,-0.0108,-0.0252,-0.0307,-0.2466,-0.0171,-0.0245,-0.0465,-0.0,-0.0037,1
1,154.0,149.0,157.0,158.0,159.0,167.0,161.0,176.0,164.0,184.0,...,-0.2105,0.0102,0.0055,-0.503,-0.01,-0.0006,-0.3122,-0.0006,0.0154,0
2,317.0,135.0,318.0,156.0,320.0,176.0,324.0,196.0,333.0,214.0,...,0.0001,-0.0015,-0.0098,-0.1621,-0.0258,-0.0278,-0.0173,-0.0018,0.0043,0
3,165.0,158.0,165.0,167.0,165.0,174.0,166.0,182.0,167.0,190.0,...,-0.0667,0.0365,0.0029,-0.1392,-0.0368,-0.0364,-0.1145,-0.0029,-0.0035,1
4,125.0,172.0,126.0,183.0,127.0,192.0,129.0,202.0,131.0,211.0,...,-0.0493,0.036000000000000004,-0.0092,-0.1548,0.0062,-0.0135,-0.1543,0.0013,-0.0082,0

In [91]:
%store panda_df

Stored 'panda_df' (DataFrame)

In [5]:
sc.stop()